prometheus:
  fullnameOverride: "prometheus"
  prometheusSpec:
    remoteWrite:
      - url: "http://prometheus-service.prometheus.svc.cluster.local:9090/api/v1/write"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "nfs-storage"
          resources:
            requests:
              storage: 20Gi

grafana:
  enabled: false

alertmanager:
  enabled: false
